TipddySurveyBundle_survey:
    resource: "@TipddySurveyBundle/Resource/config/routing/survey.yml"
    prefix: /survey

TipddySurveyBundle_question:
    resource: "@TipddySurveyBundle/Resource/config/routing/question.yml"
    prefix: /question