parameters:
#    tipddy_tipddy_survey.example.class: Tipddy\TipddySurveyBundle\Example

services:
#    tipddy_tipddy_survey.example:
#        class: %tipddy_tipddy_survey.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
